### ISSUE TITLE
ETA on release

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [Stillat/meerkat-statamic3#117]
Hi @JohnathonKoster 

Great work you are doing. We are super exited for the release of the v3 version, and actually really need it to go live with a v3 site.

Do you have an estimate on when a release will be 🙂 ?

**Comment by JohnathonKoster** [comment]
@AlexanderLindkjaer  Thanks for the kind words; I am in the documentation and final sanity check phase. Email me at john@stillat.com and I can look at getting you early access and some quick documentation to get up and running with development and testing for your release :)

The first few releases will be marked as betas and will remain that way until things are looking good enough to release to the wider marketplace :)
