### ISSUE TITLE
Hi, i got the issue

### ISSUE THREAD

**Issue by yakushenkovpaul** [Stillat/meerkat-statamic3#120]
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ErrorException 

  Invalid argument supplied for foreach()

  at vendor/stillat/meerkat/src/Configuration/Manager.php:540
    536|             if (array_key_exists($namespace, $supplementalConfiguration)) {
    537|                 $supplements = $supplementalConfiguration[$namespace];
    538|             }
    539| 
  > 540|             foreach ($configValues as $configKey => $configValue) {
    541|                 if (Str::endsWith($configKey, self::CONFIG_OVERRIDE_SUFFIX)) {
    542|                     continue;
    543|                 }
    544|

      +10 vendor frames 
  11  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by JohnathonKoster** [comment]
@yakushenkovpaul  I was able to validate this on another machine; and have released version 2.1.1-beta2 which resolves this issue :)

https://github.com/Stillat/meerkat-statamic3/releases/tag/v2.1.1-beta2
