### ISSUE TITLE
Comments not showing in control panel

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-statamic3#121]
Hey there!

I'm giving the beta a whirl and in the process of upgrading my site to Statamic v3. However, one thing I noticed is that the control panel doesn't show any of my comments. It does show that I have 113 so at least I know that the comments folder is in the right place. But clicking on All or Published does nothing. Keeps showing the now infamous "We've searched everywhere and found nothing".  :P 

So...looks like the upgrade is borked somewhere.

**Comment by JohnathonKoster** [comment]
@jeffwhitfield Can you post the contents of one of the `comment.md` files and its relative directory path? With the count showing, but not the actual contents, I think it might be an over-aggressive thread ID validator within the core that I need to tune a bit more.

Thanks!

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  I was able to recreate (hopefully the same problem), and have relaxed the thread validation rules in release 2.1.2-beta2

Let me know if the issue persists after this update or if we can close this out; thank you!

**Comment by jeffwhitfield** [comment]
Cool! Lemme pull it down and test it.  :D

**Comment by jeffwhitfield** [comment]
@JohnathonKoster Nope! Didn't work. So...here is a copy of one of my comments. If needed, I can format all of them if there's issues with the formatting. If that's the issue, that might be something to consider for people upgrading.

https://www.dropbox.com/s/l36162x6bk4uvj6/comment.md?dl=0

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  Def. a file format issue, but you shouldn't have to do the leg work. Hopefully the new 2.1.3 resolves this issue for you  and it "just works"

**Comment by JohnathonKoster** [comment]
@jeffwhitfield Just circling back here on if you're still encountering this issue; thanks!

**Comment by jeffwhitfield** [comment]
@JohnathonKoster That worked! However, now that the comments are showing, another issue has developed. Entity and HTML formatting issues. Will post a new ticket. 🤪
