### ISSUE TITLE
Comments from Statamic 2 not appearing properly in CP

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-statamic3#122]
Hola John!

Found another issue for ya. This one has to do with how some comments are showing within the control panel. Ones that have HTML formatting aren't showing at all due to a pipe at the beginning of the comment content. There's also the issue of many of them having quotes at the beginning and end of the comment. That and some that have two single-quotes within the content (due to escaping?). Regardless, these are ones that showed up fine in Statamic 2 but not in Statamic 3.

Here's what I'm seeing:

<img width="1498" alt="Screen Shot 2020-11-03 at 9 05 22 PM" src="https://user-images.githubusercontent.com/274571/98064948-0ad9e580-1e19-11eb-92f5-efad49af3984.png">

Attached is a few posts with comments you can use for further testing.

[velonut-comments.zip](https://github.com/Stillat/meerkat-statamic3/files/5485275/velonut-comments.zip)

**Comment by JohnathonKoster** [comment]
@jeffwhitfield Thanks for the sample data; I'll have a new beta release for this within the next day or so 🙂

**Comment by jeffwhitfield** [comment]
@JohnathonKoster You bet! And if you need any more sample comments feel free to hit me up.  :D
