### ISSUE TITLE
Template variable for date/timestamp of comment

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-statamic3#123]
Hey John! Got a few other issues that popped up. This time with the templating.

With the previous version, I could use ```{{ date }}``` and add the formatting parameter for the date/timestamp of the comment. This doesn't work with the current version so...err...what's the new template variable for this?  :P 

Thx in advance! Keep up the great work!  :D

**Comment by JohnathonKoster** [comment]
I'll review some items from the old version and what's available in the new version and add some things back in to make transitioning much easier. For the v2 version, the `{{ comment_date }}` variable should do the trick, though.

A full list of all available variables can be found here: https://meerkatcomments.com/docs/default-variables

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  Available in 2.1.8-beta2 :)
