### ISSUE TITLE
Template tag for gravatars missing

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-statamic3#124]
Hey John! Just one more for ya related to templates.

The previous version had a ```{{ meerkat:gravatar }}``` that could be used to display a Gravatar image. I see the Gravatar class in the code but...err...how does that translate to an actual template tag?  :P 

Thanks man!  :D

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  Currently not supported in the template, but will be available in the next beta release 👍 

I'll keep a `meerkat:gravatar` Antlers tag around, but have been thinking of ways to make this customizable for other Meerkat addon developers (e.g., something like `{{ meerkat:avatar service="gravatar" }}` )

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  Available in 2.1.8-beta2 :)
