### ISSUE TITLE
Compatibility with Captcha add-on

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-statamic3#125]
Hey John,

Still in the process of converting my site to Statamic v3. Taking a little more time. One more thing I'm trying to work through is getting the new [Captcha](https://statamic.com/addons/aryeh-raber/captcha) add-on working with Meerkat comments and replies. 

First, what is the name of the form to target? Is it just `meerkat`?

Second, could you test Meerkat with this add-on to see if there are any issues?  Honestly, this is my first line defense to avoiding spam. Without it, I get a barrage of garbage hitting my site. Best to throw an hCaptcha in to avoid bogus submissions from bots.  :D

**Comment by jeffwhitfield** [comment]
Alrighty, everything else has tested out fine (well....except one last low priority thing!) This is the last thing to get working before I can launch into production. 

I've tried setting the Captcha config to use `meerkat` for the forms setting. No workie! :P Getting the Captcha add-on to work would really, really help ward off the barrage of bot submissions I usually get without it. 

Add-on is working great, John! Great work! Just one last thing and I'm home free!  :D

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  Just an update on this one :)

Meerkat 2 does not rely on the built-in Statamic form system (even though it pretends to, very well). I am working on an update today that improves Meerkat's form impersonation features that will enable it to work seamlessly with third-party Statamic form addons

**Comment by jeffwhitfield** [comment]
@JohnathonKoster Cool, man!  Yeah, that would be a great addition to the add-on. No doubt a lot of folks (me included!) would like to see ways to enhance the forms with things like Captcha. Granted, there is the setting that turns off email notifications for spam comments. But, even then, it's still good to ward off unnecessary comments through basic form protection. Eliminates the extra work of having to constantly go in and kill off spam comments. :P

**Comment by JohnathonKoster** [comment]
This is now generally available in version 2.1.13-beta2. This update also improves the compatibility with dynamic reply forms for both reCaptcha and hCaptcha.

**Comment by JohnathonKoster** [comment]
The form name is "Meerkat" 😄
