### ISSUE TITLE
Error: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-statamic3#129]
Hey John, 

Just got a big error after migrating the site to a dev environment on a DigitalOcean server. Whenever a comment is created, I get an "Invalid argument supplied for foreach()" error. Here's an example:

https://dev.velonut.com/blog/review-ritchey-wcs-beacon-handlebars#comments

To verify this, I removed all comments and started from scratch (it is a dev environment after all! :P ). Still getting errors for any comments present on any post. Here's a sample of the comment that causes the error on the URL above.

[velonut-comment.zip](https://github.com/Stillat/meerkat-statamic3/files/5611093/velonut-comment.zip)

What's weird is that the error doesn't happen locally on my Mac using MAMP. It's only on the DigitalOcean server so I'm not quite sure what to make of it. Some weird security setting getting in the way of Meerkat's ability to read the comment files?

**Comment by JohnathonKoster** [comment]
Interesting one! I'll take a look at this and see if I can get a fix out with the release later today. In the meantime, are there any empty directories in the path it's searching in, by chance?

**Comment by jeffwhitfield** [comment]
Nope! Cleared out all comments. That one comment is the only one.

**Comment by JohnathonKoster** [comment]
I have been unable to reproduce the exact issue causing this, but version 2.1.13-beta2 includes some protections for when the `glob` function return` false` as its return value.

Let me know if the issue clears up after 2.1.13-beta2, or if further investigation will be required on the server & directory setup.

Thanks!
