### ISSUE TITLE
Assets broken in prod

### ISSUE THREAD

**Issue by stancl** [Stillat/meerkat-statamic3#152]
Hey,

Meerkat's CP features work for me locally, but not in production. 

Some buttons are missing:
<img width="340" alt="Screen Shot 2021-01-25 at 21 07 38" src="https://user-images.githubusercontent.com/33033094/105759934-5bad3600-5f51-11eb-8ab9-2c7c4f1c43ad.png">

User profiles don't load, reply/publish/... buttons don't show, etc.

I noticed this console error:

<img width="961" alt="Screen Shot 2021-01-25 at 21 06 47" src="https://user-images.githubusercontent.com/33033094/105759843-3d473a80-5f51-11eb-9aa8-5615f6022d1a.png">

Seems like it's an issue with the prod asset build?

**Comment by JohnathonKoster** [comment]
@stancl 

Hi there - which version of Meerkat and Statamic do you have installed?

After logging into your Control Panel, do you receive any errors our output if you visit:

```
<YOUR_DOMAIN>/meerkat/js/cpConfiguration.js
```

Thanks!

**Comment by stancl** [comment]
`cpConfiguration.js` loads correctly and I'm using the latest versions of Meerkat and Statamic, updated both.

**Comment by JohnathonKoster** [comment]
Interesting - I am having trouble replicating this. Are there any errors reported on the Network tab in devtools?

Thanks!

**Comment by stancl** [comment]
No errors in network tab, only console.

I also noticed that on `/cp/addons/meerkat/settings` I see only the General tab. In my local environment I see all of the tabs.

Seems like the property with user preferences goes missing for some reason.

**Comment by JohnathonKoster** [comment]
I've released version v2.2.1-beta3 which handles the error that shows up the console in a better way, but I think there might be something else going on. Can you verify that the web server's user account has read/write access to the following directories:

* config/meerkat
* content/comments
* storage/meerkat

Sometimes the command line and web server users are different, and cause some interesting, unpredictable permissions issues that have weird side effects. I've also added a new Meerkat Installation Validator utility to the Statamic Control Panel to help track down potential issues (and will add more checks over time):

![meerkat_validator_utility](https://user-images.githubusercontent.com/5232890/105933370-e8b8c380-6013-11eb-819c-ccd163215315.png)

**Comment by stancl** [comment]
@JohnathonKoster The validator shows all green checks.

I think that when deploying once I accidentally ran something like `php artisan optimize`, could it be that? I did clean the cache afterwards though.

**Comment by stancl** [comment]
I ssh'd into the server and ran `git status` to see if maybe some stuff is different on the server, and I found a file in `storage/meerkat/logs/`. It says:

```
C:37:"Stillat\Meerkat\Core\Logging\ErrorLog":197:{{"id":"bd609bd5-2413-4bc1-9979-3659b37dbf21","ec":"02-002","ctx":"{\"msg\":\"Could not read response from Akismet API response.\",\"details\":\"invalid\"}","date":161
```

Is that relevant?

**Comment by stancl** [comment]
Also might be relevant:

<img width="822" alt="Screen Shot 2021-01-28 at 12 19 18" src="https://user-images.githubusercontent.com/33033094/106131505-0e081780-6163-11eb-96eb-68c43ad8575d.png">

**Comment by stancl** [comment]
Hmm, it seems like the uncompiled version sets `UserPreferences` to an object, but the prod version sets it to null?
<img width="589" alt="Screen Shot 2021-01-28 at 12 20 51" src="https://user-images.githubusercontent.com/33033094/106131706-4f002c00-6163-11eb-8458-8dbce4713508.png">

<img width="299" alt="Screen Shot 2021-01-28 at 12 21 03" src="https://user-images.githubusercontent.com/33033094/106131714-50c9ef80-6163-11eb-96a9-5686f9399299.png">

**Comment by stancl** [comment]
And another thing I noticed: while `meerkat/js/cpConfiguration.js` is accessible, it's not requested in prod but only locally.

<img width="146" alt="Screen Shot 2021-01-28 at 12 29 22" src="https://user-images.githubusercontent.com/33033094/106132654-7efbff00-6164-11eb-82a6-071c23053f71.png">
<img width="216" alt="Screen Shot 2021-01-28 at 12 29 06" src="https://user-images.githubusercontent.com/33033094/106132649-7dcad200-6164-11eb-8200-eec072c1b39a.png">

Prod doesn't have the `<script>` tag for `cpConfiguration.js`. It's right beneath my seo-pro include which works in both local and prod

**Comment by stancl** [comment]
<img width="791" alt="Screen Shot 2021-01-28 at 12 44 28" src="https://user-images.githubusercontent.com/33033094/106134252-92a86500-6166-11eb-8f90-eebda70f110d.png">

This is weird though, Statamic seems to register the vendor asset and route at the same time? So if the route works, but the asset is not loaded, that make sense 🤔

**Comment by stancl** [comment]
Aha, I had to clear route cache separately.

It kept the old route info, but the asset is registered in a route file.

Now it works :)

Didn't realize that `php artisan route:clear` needs to be run separately. Seems like this was an issue on my part having cached the assets, so apologies for that and thanks for the help!

**Comment by JohnathonKoster** [comment]
@stancl  No problem - and thanks for posting the solution  - this was a tricky one!

I'll get this written up as a possible installation issue when migrating a Meerkat install to different environments. Thanks for your incredible investigation into that! :)

**Comment by JohnathonKoster** [comment]
Follow with responses taken after this issue in Meerkat v2.2.2-beta3 and v2.2.3-beta3

v2.2.2-beta3:

* Addresses production bundling issues

vs2.2.3-beta3:

* Meerkat's installation validator will now detect route caching issues, and report all known potential issues it can
* Site administrators can now clear the route cache from the installation validator (only if that route is available in their environment)
* The installation validator provides instructions on how to clear the route cache manually, or by using Artisan
* Meerkat can now automatically recover from simple route caching issues itself when loading either the Control Panel's Comment Manager or Meerkat's Configuration Panel. Meerkat will detect the route caching issues ahead of time, and clear the route cache before the response is sent to the user.

![updated_install_validator](https://user-images.githubusercontent.com/5232890/106357483-ebddd900-62cb-11eb-8c51-e427cf1f9d22.png)
