### ISSUE TITLE
Invalidate cached page after publishing/unpublishing/deleting

### ISSUE THREAD

**Issue by AndreasSchantl** [Stillat/meerkat-statamic3#182]
As of now, the cache is not invalidated upon publishing/unpublishing or deleting a comment. Resulting in the comment still being shown after doing one of those actions.

This should work by firing an ``EntrySaved`` event. If I get time to, I'll do a PR

**Comment by JohnathonKoster** [comment]
@AndreasSchantl  Adding this to your site's `meerkat/events.php` file should do the trick:

```php
<?php

use Stillat\Meerkat\Support\Facades\Meerkat;
use Stillat\Meerkat\Core\Contracts\Comments\CommentContract;
use Statamic\Facades\Entry;
use Statamic\Events\EntrySaved;

function invalidateEntryCache(CommentContract $comment) {
    $entryId = $comment->getThreadId();
    $statamicEntry = Entry::find($entryId);

    if ($statamicEntry !== null) {
        EntrySaved::dispatch($statamicEntry);
    }
}

Meerkat::onCommentSoftDeleted(function ($comment) {
    invalidateEntryCache($comment);
});

Meerkat::onCommentRemoved(function ($comment) {
    invalidateEntryCache($comment);
});

// This is called on both updating and creating
Meerkat::onShouldHandle(function ($comment) {
    invalidateEntryCache($comment);
});
```

If you cannot get those events to fire in your development or production environment (or cannot catch them) - you can force Meerkat to not try and attempt to defer event execution by creating a file at `config/meerkat/internals.php` (this is not published by default) and setting the content to:

```php
<?php

return [
    'runDelayedMutationsSync' => true
];

```

**Comment by AndreasSchantl** [comment]
Thanks! Unfortunately, the events aren't listened to, even if ``runDelayedMutationSync`` set to true. Any idea why?

**Comment by JohnathonKoster** [comment]
That's interesting - 

A few quick idea come to mind:

* Maybe the `meerkat/events.php` file isn't actually being loaded - adding a `dd()` (or equivalent) statement somewhere in the file outside of the event handlers would help eliminate this
* Adding a `dd($comment)` inside the handlers, before the `invalidateEntryCache` method call would eliminate the events actually not firing, and point to something in the `invalidateEntryCache` method going wrong (possibly `null` entry?)

Something else could be breaking, and causing it to fail silently - release 2.3.0-beta3 made the debugging experience a lot better on local setups (where it will re-throw exceptions, and dump errors to Spatie's Ray, if it's available on the project). I'll have time later this evening (US Central Time) to do some more thorough investigations if the issue persists

**Comment by AndreasSchantl** [comment]
I have tried the latter option already before commenting that it doesn't work. What I have just tried though is adding a dd outside the listeners. The file is loaded! So it must be something else.

**Comment by JohnathonKoster** [comment]
Thanks for verifying that - I'll do some investigation later and let you know what I discover. 

Definitely shouldn't be something you should have to fight with 🙂

**Comment by AndreasSchantl** [comment]
Big thanks ❤️

**Comment by JohnathonKoster** [comment]
I have been doing some quick tests on a fresh Meerkat and Statamic install on a different computer (to eliminate any possible files that might exist on the dev machine) - and cannot reproduce this issue

Could I get some more information for when I take a deep dive later?

* Statamic Version
* PHP Version
* Your Statamic cache settings
* Are you able to listen for and handle Statamic-fired events?

If you are able to create a small sample project that reproduces this issue feel free to email me a ZIP directly at john@stillat.com

In either case, if I cannot track down the root cause of the events today, I will get something added to Core that will fire the Statamic event for you

**Comment by AndreasSchantl** [comment]
Sure, here the infos:

- Statamic Version 3.0.45
- PHP 7.4.13
- Cache is set to 'half' as of now
- I do have a usual listener in place that renames files after them being uploaded

Tell me if that helps to reproduce the problem. Otherwise I'll indeed create a small example page for you.

**Comment by JohnathonKoster** [comment]
@AndreasSchantl  I've release v2.4.0-beta3 just now which makes these changes:

* Removes deferred event handlers entirely until a better/more reliable solution can be implemented
* Writes event names to the storage/meerkat/logs/events.log file when in debug mode
* Fires Statamic's EntrySaved on comment context's when changes are made to a comment (or it is created, removed, etc.)
* Adds a contexts list to the CommentRemovalEventArgs - which will contain a list of all unique context identifiers for that event

I still have not been able to reproduce that issue - so if you can get a small example one that does that would be great. This new update also writes the event names to a log file - maybe something weird is happening where the event names are not what's expected by all the different pieces?

Let me know how this update works for you!

**Comment by AndreasSchantl** [comment]
That worked great! Thanks.
