### ISSUE TITLE
Possible error when sending comment with non-valid data in Statamic 3.1

### ISSUE THREAD

**Issue by phsteffen** [Stillat/meerkat-statamic3#186]
Hi Johnathon,

I'm doing a little testing with your cool plugin based on a Statamic v3.1 installation.  
Now when I place a comment form on a page and make an invalid input in a field -  
for example, I write an invalid email address in the email field, then I get the following error:

```
Stillat\Meerkat\Forms\FormHandler::validate
vendor/stillat/meerkat/src/Forms/FormHandler.php:190
```

And Laravel gets stuck in the exception.

If I fill in all fields validly, then everything works fine too and I see the comment in the Statamic backend.

In Statamic 3.0 with meerkat-statamic3 v2.4.0-beta3 it still worked from my point of view.

**Comment by rolinbos** [comment]
The fix for this problem is in this PR: https://github.com/Stillat/meerkat-statamic3/pull/188
