### ISSUE TITLE
Error validating submission data

### ISSUE THREAD

**Issue by MeMattStone** [Stillat/meerkat-statamic3#189]
Statamic: v3.1.33
Meerkat: v2.4.6-beta3

When I submit a comment I get the following error:

```
ErrorException
in_array() expects parameter 2 to be array, string given
```

The offending code is `vendor/stillat/meerkat/src/Forms/FormHandler.php` line 166:

```php
        // Merge in field rules
        foreach ($this->getFields() as $field_name => $field_config) {
            $field_rules = array_get($field_config, MeerkatForm::KEY_FORM_CONFIG_VALIDATE);

            if ($field_rules) {
                if (in_array('sometimes', $field_rules)) {
                    if (array_key_exists($field_name, $submissionData)&& $submissionData[$field_name] !== null) {
                        $rules[$field_name] = $field_rules;
                    }
                } else {
                    $rules[$field_name] = $field_rules;
                }
            }

            // Makes the names prettier.
            $attributes[$field_name] = array_get(
                $field_config,
                MeerkatForm::KEY_FORM_CONFIG_DISPLAY_NAME, $field_name
            );
        }
```

The value of $field_rules is a string: `required|max:100|min:1` so the check for `sometimes` using `in_array` fails.

**Comment by MeMattStone** [comment]
Edited the above to show I'm running v2.4.6-beta3 however the Meerkat Installation Validator reports this version as v2.4.5-beta3

**Comment by JohnathonKoster** [comment]
This has been correct in 2.4.7-beta3

The version reported on the validator may diverge from that in the composer.json file. I tend to only increment the internal version when absolutely necessary since it will trigger a republish of assets on all installations :)
