### ISSUE TITLE
Giant filter icon

### ISSUE THREAD

**Issue by katjapvl** [Stillat/meerkat-statamic3#201]
After installing Meerkat into a site using a starter kit, like Starter's Creek, Cool Writings, etc., I am met with the following, massive, filter icon:

![filter-icon](https://user-images.githubusercontent.com/45769506/155603840-18e431c0-06db-4f88-8ac6-0336c5574e5a.png)

Setting a `max-width` of `15px` on `.meerkat__filter-toggle` resolves this.

**Comment by JohnathonKoster** [comment]
Thanks for the report! I will get your fix published in a release later today :)
