### ISSUE TITLE
Option to define the "from address" for the comment submitted email

### ISSUE THREAD

**Issue by shoored** [Stillat/meerkat-statamic3#205]
Hello,

When the send email option is enabled, an email is sent whenever a new comment is submitted.
The from address for this email is coded to be the email address from the comment submitter.

On our transactional email service we can only use email addresses from the same domain as our website which now results in errors and emails not being sent.

Is it possible to add an option to set the "from address" to either the comment submitter or a custom one?

**Comment by JohnathonKoster** [comment]
@shoored  Thanks for reaching out! I've added a new configuration item and released it as `2.6.0` that will allow you to customize the "From" email address.

You can learn more about this new configuration item from the release notes: https://github.com/Stillat/meerkat-statamic3/releases/tag/v2.6.0

I will leave this issue open for now to make sure this change fits your needs.

Thanks!

**Comment by shoored** [comment]
@JohnathonKoster Thanks so much for the quick response! I have just tested this and can confirm it works as expected. 

For me personally, just a config file entry is more than ok. Perhaps other customers would like a CP config option but as far as I'm concerned you can close the issue. Thanks a bunch!
