### ISSUE TITLE
Post to /!/Meerkat/socialize not found

### ISSUE THREAD

**Issue by Bahbv** [Stillat/meerkat-statamic3#212]
Hello,

After installing Meerkat with composer and following the intergration guide on https://meerkatcomments.com/docs/integrating-meerkat my comment form doesn't post anything. Looking at the network activity it shows the path the form is posting to is not found.  
  
![afbeelding](https://user-images.githubusercontent.com/12693117/203969729-edfa8182-6e0b-4877-898f-c60b135b1162.png)
  
I've checked if all the meerkat files are there and they are. I've also tried reinstalling but without effect.  
I'm on localhost and haven't changed anything in the meerkat config files. Also the Meerkat installation validator doesnt show any errors. 
  
```
Statamic Version | 3.3.58
Meerkat Version | 2.4.11
Apache/2.4.47 (Win64) OpenSSL/1.1.1k mod_fcgid/2.3.10-dev
```
  
The `/storage/meerkat/logs/` is full of files containing things like 
```
C:37:"Stillat\Meerkat\Core\Logging\ErrorLog":176:{{"id":"0ba6ce99-c6a1-4987-bc76-a857cc277604","ec":"03-002","ctx":"{\"msg\":\"f9438d37-011a-4e82-8718-f90f9a0fdf2d\",\"details\":\"\"}","date":1669373125,"type":1,"action":null}}
```

Is Meerkat not supported on this version?

**Comment by JohnathonKoster** [comment]
Hey there!

For the `POST`, can you try a `php artisan route:clear` to ensure there are no cached routes?

The error posted seems unrelated. The `03-002` indicates it can't find any details surrounding an entry. Generally safe to ignore, but a `php please stache:clear` helps to reduce those

**Comment by Bahbv** [comment]
Hi Johnathon,

Thanks for your reaction, unfortunately i had already tried this without any results. I also tried refreshing the whole laravel cache.
Weird thing is the POST does work, since i get the validation rules when i forget a field like:

![afbeelding](https://user-images.githubusercontent.com/12693117/204020652-55f2293c-8df8-4c50-aeaa-caa9cf2bb110.png)

But when all fields all filled in the page refreshes but nothing happens. The backoffice /cp doesnt show any new comments and the `{{ success }}` messages isn't appearing.

Thanks.

**Comment by Bahbv** [comment]
Initially i tried making a page via a statamic route in the web.php. I used the `{{ meerkat:create }}` tag in here. Since the form, and the error messages rendered I thought this was possible, found out it was not. Now I've made a 'real' page with a new blueprint and the commenting system works flawlessly!

Sorry for the issue, seems like it was my own fault ;)
