### ISSUE TITLE
thread:in filter not working as expected

### ISSUE THREAD

**Issue by Bahbv** [Stillat/meerkat-statamic3#215]
Hello,

After reading through the documentation about filters i found the `thread:in` filter. Im trying to use  it to show comments from another page/entry like so
```
{{ meerkat:responses filter="thread:in(84a86222-19a7-414e-80da-acc8c842eb73)" }}
    {{ comments }}
       <!-- Comment here -->
    {{ /comments }}
{{ /meerkat:responses }}
```

However this gives me an `Array to string conversion` errorExeption.
Is there another way to show comments from another page?

**Comment by JohnathonKoster** [comment]
Hello, there!

I will look into this. What version of Statamic are you using?

Thanks! 🙂

**Comment by Bahbv** [comment]
Hi, that would be great!  
  
Statamic version 3.3.60
Meerkat 2.6.1

Cheers.

**Comment by Bahbv** [comment]
Hi,

If you didn't had the change to look into this problem, Do you have a general direction for me so i could could take a look myself?
This is a great plugin but I need to get comments from another page.

Thanks!

**Comment by JohnathonKoster** [comment]
This can be accomplished in Meerkat 2 by adding a hidden value to the entry's YAML like so:

```markdown
---
meerkat_share_comments:
  - 84a86222-19a7-414e-80da-acc8c842eb73
---
```

The exception message will be resolved in the next version (it is failing producing an error message). In Meerkat 3, the following will be possible to make this easier:

```antlers
{{ meerkat:responses from_thread="84a86222-19a7-414e-80da-acc8c842eb73" }}
   {{ comments }}
      {{ content }}
   {{ /comments }}
{{ /meerkat:responses }}
```
