### ISSUE TITLE
Comment list: View entry link does not take custom cp route into account

### ISSUE THREAD

**Issue by juliawarnke** [Stillat/meerkat-statamic3#225]
The "View Entry"-Link inside the comment list does not work, when custom control panel route is defined.

![image](https://user-images.githubusercontent.com/44929138/222083064-455d7042-1b6a-410d-aac8-e341979b4f5b.png)

I configured my control panel route to be something different than `cp`. But the [template](https://github.com/Stillat/meerkat-statamic3/blob/master/resources/ui/src/App/Components/CommentActions/template.html#L155) does always point to `cp/meerkat/redirect...`

**Comment by JohnathonKoster** [comment]
Hi there! This should now be resolved in version `2.6.4`

After installing this version, you may need to clear your route cache, if it exists:

```bash
php artisan route:clear
```

**Comment by juliawarnke** [comment]
Thank you very much. That was blazing fast! 🚀
