### ISSUE TITLE
Perfomance issue with /mapi/meerkat/reporting/overview request

### ISSUE THREAD

**Issue by Krzemo** [Stillat/meerkat-statamic3#229]
@JohnathonKoster
We've been using Meerkat on a constantly growing (content wise) website.
Some time ago we encountered a performance problems and investigation lead us to `/mapi/meerkat/reporting/overview` request made on each CP url.
We have close to 2k entries in on collection and not much less comments and it seems like calculating overview stats on the fly became too demanding basically choking our VPS.
I realize this may not be trivial to fix, but maybe keeping data for that json precalculated somewhere and updating via queue job on comments update might be an idea to consider.
We have ugly "workaround" in place by serving dummy json from nginx config so this is not performance issue for us anymore ;)

**Comment by JohnathonKoster** [comment]
The performance of this endpoint has been improved in the following versions:

Statamic 3 (backport): 2.7.0
Statamic 4: 3.1.0

Some internal improvements were made to reduce the overall amount of augmentation that needs to happen for the Statamic entries. Additionally, the reporting/overview endpoint was refactored to not require as much additional information, greatly improving its performance.
