### ISSUE TITLE
Compatibility with Statamic 4 planned?

### ISSUE THREAD

**Issue by florianbrinkmann** [Stillat/meerkat-statamic3#231]
Hi,

just wanted to ask if there are plans for a Statamic 4 version of Meerkat?

Best,
Florian

**Comment by JohnathonKoster** [comment]
Hi there!

Its something that is on the roadmap - just taking some time to think through how I want that to look going forward (thinking of switching Meerkat to use a database going forward, and using SQLite by default)

**Comment by florianbrinkmann** [comment]
Great, thanks! :)

**Comment by m-emelchenkov** [comment]
I am testing Statamic 4 right now and I would like to test your comments as well, @JohnathonKoster. Please, if you already have a public beta version, how to install? I'd also want to ask if your new version will allow to login users to the comment system via OAuth (i.e. Facebook, Apple, Vkontakte and so on).

**Comment by JohnathonKoster** [comment]
Hi there!

I have no public beta version at this time - and am working to have more details available over the next few weeks. I do not have any plans at this time to integrate OAuth systems directly within Meerkat; there are a number of hooks available where this could likely be implemented within the site itself (albeit, non-trivially).

**Comment by JohnathonKoster** [comment]
Statamic 4 support has launched version 3 🥳
