### ISSUE TITLE
Comments page does not load

### ISSUE THREAD

**Issue by ryanmitchell** [Stillat/meerkat-statamic3#234]
We are finding the comments page does not load for us at all - it just spins:

<img width="1488" alt="Screenshot 2023-07-28 at 09 20 16" src="https://github.com/Stillat/meerkat-statamic3/assets/51899/8f21da7c-075f-481c-a9f8-7490d10db3a1">

Comments can be added on the front end, the configure page works fine, and we get a 'count' elsewhere in the CP. But the overall comments view does not load.

We have around 1500 blog posts, but less than 100 comments. There are unfortunately no errors in the logs that are relevent to Meerkat.

The call to mapi/meerkat/comments/search does (eventually) return results, however the first call to /mapi/meerkat/reporting/overview? fails, though there seem to be multiple and later ones succeed.

Is there anything that can be done?

**Comment by JohnathonKoster** [comment]
Hey there! There are some performance issues I’ve been investigating over the past few days that are causing this.

The API wrapper I’m using also has an aggressive timeout, which I will be adjusting in the next release, but also want to improve the performance issues as well. Looking to be mid-end of next week for this improvement 👍

**Comment by JohnathonKoster** [comment]
Resolved in the following versions:

Statamic 3 (critical backport): 2.7.0
Statamic 4: 3.1.0

**Comment by ryanmitchell** [comment]
Just tested and thats working a lot better now, thank you!
