### ISSUE TITLE
Docs mention "orderby", when the actual parameter seems to be "order"

### ISSUE THREAD

**Issue by el-schneider** [Stillat/meerkat-statamic3#235]
Hi, just stumbled open this and wanted to let you know. 

Haven't checked if there are other occurences, but here are some: https://stillat.com/meerkat/sorting-comment-threads

**Comment by pixels-for-breakfast** [comment]
I can confirm that 'orderby' does not work, but 'order' does!

**Comment by JohnathonKoster** [comment]
Thanks for the nudge on this - the docs could use some love. I'll add this to my list for this upcoming weekend!

**Comment by JohnathonKoster** [comment]
Fixed!
