### ISSUE TITLE
Call to undefined function Stillat\Meerkat\Forms\array_get()

### ISSUE THREAD

**Issue by pixels-for-breakfast** [Stillat/meerkat-statamic3#240]
Hi,

I have the same issue as described [here](https://github.com/Stillat/meerkat-statamic3/issues/212) (Post to /!/Meerkat/socialize not found), which is:
"Call to undefined function Stillat\Meerkat\Forms\array_get()"

I have a Statamic v5.5.0 installation. Installing the addon gave me no troubles, and the form shows fine on the page. I've moved the form to some other templates and tried on various routes/pages and I've also tried the suggestions from [here](https://github.com/Stillat/meerkat-statamic3/issues/212#issuecomment-1327540418), but to no avail.

Any other ideas? Thanks!

**Comment by JohnathonKoster** [comment]
Thanks for the report! I've refactored those two function calls and released v3.2.2 to address this issue 👍

**Comment by pixels-for-breakfast** [comment]
Thanks for the swift response and the quick fix. I can indeed confirm it now works as expected.
