### ISSUE TITLE
Class "\Stillat\Meerkat\Http\Controllers\Api\TelemetryController" does not exist

### ISSUE THREAD

**Issue by colq2** [Stillat/meerkat-statamic3#243]
Hey! I get this error when running `php artisan route:list`. Just had a quick look and the controller is gone but used in the RouteCacheValidator.

**Comment by colq2** [comment]
Also just saw that it is also used in the `web.php` file.

**Comment by JohnathonKoster** [comment]
Thanks for the report! Should be good to go as of 3.2.4 👍
